apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment #pod name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-k8s # label for pod
  template:
    metadata:
      labels:
        app: kubernetes-k8s
    spec:
      containers:
        - name: kubernetes-tutorial
          image: kubernetes-k8s:v1
          ports:
          - containerPort: 3000
          env:          #env variables
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE
                  name: hello-config
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: API_KEY
                  name: hello-secret