apiVersion: v1
kind: Service
metadata:
  name: hello-service #pod name
spec:
  selector:
    app: kubernetes-k8s #pod label
  ports:
    - port: 80 #service
      targetPort: 3000 #port number of the container
  type: LoadBalancer